# Generated by Django 6.0.3 on 2026-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
